# Generated by Django 5.1.2 on 2024-11-04 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a2_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exampleModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='relationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a2_model.mymodel')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a3_relation.examplemodel')),
                ('table', models.ManyToManyField(related_name='category', to='a2_model.mytable')),
            ],
        ),
    ]
