# Generated by Django 5.1.2 on 2024-11-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(null=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('cgpa', models.FloatField(verbose_name='CGPA')),
                ('profile', models.URLField(blank=True, null=True)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='myTable',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
