# Generated by Django 5.1.2 on 2024-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='myApp/media/'),
        ),
    ]
